-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 17:04:29 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema JG_Confeccoes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema JG_Confeccoes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `JG_Confeccoes` DEFAULT CHARACTER SET utf8 ;
USE `JG_Confeccoes` ;

-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`Item` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Tamanho` ENUM("P", "M", "G") NOT NULL,
  `Categoria` VARCHAR(45) NOT NULL,
  `Preco` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  `Imagem` VARCHAR(145),
  PRIMARY KEY (`idItem`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`Funcionario` (
  `Email` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(80) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`TipoEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`TipoEntrega` (
  `Tipo` INT NOT NULL,
  `Tempo` INT NOT NULL,
  `ValorFrete` FLOAT NOT NULL,
  PRIMARY KEY (`Tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`Cliente` (
  `Email` VARCHAR(45) NOT NULL,
  `Cpf` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(1) NOT NULL,
  `Senha` VARCHAR(45) NOT NULL,
  `Endereco` VARCHAR(80) NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `Telefone` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`Pedido` (
  `idPedido` INT NOT NULL,
  `Status` VARCHAR(45) NOT NULL,
  `Valor` FLOAT NOT NULL,
  `EnderecoEntrega` VARCHAR(80) NOT NULL,
  `TipoEntrega_Tipo` INT NOT NULL,
  `Cliente_Email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPedido`),
  INDEX `fk_Pedido_TipoEntrega1_idx` (`TipoEntrega_Tipo` ASC) ,
  INDEX `fk_Pedido_Cliente1_idx` (`Cliente_Email` ASC) ,
  CONSTRAINT `fk_Pedido_TipoEntrega1`
    FOREIGN KEY (`TipoEntrega_Tipo`)
    REFERENCES `JG_Confeccoes`.`TipoEntrega` (`Tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente1`
    FOREIGN KEY (`Cliente_Email`)
    REFERENCES `JG_Confeccoes`.`Cliente` (`Email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `JG_Confeccoes`.`Item_has_Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `JG_Confeccoes`.`Item_has_Pedido` (
  `Item_idItem` INT NOT NULL,
  `Pedido_idPedido` INT NOT NULL,
  `Quantidade` INT NOT NULL,
  PRIMARY KEY (`Item_idItem`, `Pedido_idPedido`),
  INDEX `fk_Item_has_Pedido_Pedido1_idx` (`Pedido_idPedido` ASC) ,
  INDEX `fk_Item_has_Pedido_Item_idx` (`Item_idItem` ASC) ,
  CONSTRAINT `fk_Item_has_Pedido_Item`
    FOREIGN KEY (`Item_idItem`)
    REFERENCES `JG_Confeccoes`.`Item` (`idItem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Pedido_Pedido1`
    FOREIGN KEY (`Pedido_idPedido`)
    REFERENCES `JG_Confeccoes`.`Pedido` (`idPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
